// UI components for extensions
export {
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	type CustomEditorOptions,
	CustomMessageComponent,
	DynamicBorder,
	type EditorBottomStatus,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsContext,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
export { InteractiveMode, type InteractiveModeOptions } from "./modes/interactive/interactive-mode.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeAppearance,
	type ThemeBg,
	type ThemeColor,
	type ThemeStyle,
	type ThemeToken,
} from "./modes/interactive/theme/theme.ts";
export { resourceThemeAdapter } from "./presentation/resource-theme-adapter.ts";
export { copyToClipboard } from "./utils/clipboard.ts";
