import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { writeGeneratedModelCatalog } from "../scripts/write-generated-model-catalog.ts";

const temporaryRoots: string[] = [];

afterEach(() => {
	for (const root of temporaryRoots.splice(0)) rmSync(root, { force: true, recursive: true });
});

describe("generated model catalog output", () => {
	it("preserves the generated wrapper and aggregate catalog format", () => {
		const root = mkdtempSync(join(tmpdir(), "candy-model-catalog-"));
		temporaryRoots.push(root);
		const providersDir = join(root, "src", "providers");
		mkdirSync(providersDir, { recursive: true });
		writeFileSync(join(providersDir, "obsolete.models.ts"), "obsolete");
		writeFileSync(join(root, "src", "models.generated.ts"), "previous");

		const restore = writeGeneratedModelCatalog(providersDir, root, ["acme"]);

		expect(
			readFileSync(join(providersDir, "acme.models.ts"), "utf8"),
		).toBe(`// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/acme.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const ACME_MODELS: ChatModelCatalog<typeof values, "acme"> =
	flattenChatModelCatalog("acme", values);

export const ACME_IMAGE_MODELS: ImageModelCatalog<typeof values, "acme"> =
	flattenImageModelCatalog("acme", values);

export const ACME_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "acme"> =
	flattenClassifierModelCatalog("acme", values);
`);
		expect(
			readFileSync(join(root, "src", "models.generated.ts"), "utf8"),
		).toBe(`// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ACME_CLASSIFIER_MODELS, ACME_IMAGE_MODELS, ACME_MODELS } from "./providers/acme.models.ts";

export const MODELS: {
	readonly "acme": typeof ACME_MODELS;
} = {
	"acme": ACME_MODELS,
};

export const IMAGE_MODELS: {
	readonly "acme": typeof ACME_IMAGE_MODELS;
} = {
	"acme": ACME_IMAGE_MODELS,
};

export const CLASSIFIER_MODELS: {
	readonly "acme": typeof ACME_CLASSIFIER_MODELS;
} = {
	"acme": ACME_CLASSIFIER_MODELS,
};
`);
		expect(() => readFileSync(join(providersDir, "obsolete.models.ts"), "utf8")).toThrow();
		restore();
		expect(readFileSync(join(providersDir, "obsolete.models.ts"), "utf8")).toBe("obsolete");
		expect(readFileSync(join(root, "src", "models.generated.ts"), "utf8")).toBe("previous");
	});
});
