import { readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function writeGeneratedModelCatalog(providersDir: string, packageRoot: string, providerIds: string[]): () => void {
	const previousShardContents = new Map(
		readdirSync(providersDir)
			.filter((entry) => entry.endsWith(".models.ts"))
			.map((entry) => [entry, readFileSync(join(providersDir, entry), "utf8")] as const),
	);
	const aggregatorPath = join(packageRoot, "src/models.generated.ts");
	const previousAggregator = readFileSync(aggregatorPath, "utf8");
	const restore = () => {
		for (const entry of readdirSync(providersDir)) {
			if (entry.endsWith(".models.ts")) rmSync(join(providersDir, entry));
		}
		for (const [entry, content] of previousShardContents) {
			writeFileSync(join(providersDir, entry), content);
		}
		writeFileSync(aggregatorPath, previousAggregator);
	};

	try {
		const generatedHeader = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;
		const catalogConstName = (providerId: string) => `${providerId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_MODELS`;
		const imageCatalogConstName = (providerId: string) =>
			`${providerId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_IMAGE_MODELS`;
		const generatedShardFiles = new Set<string>();

		for (const providerId of providerIds) {
		let output = generatedHeader;
		output += `import values from "./data/${providerId}.json" with { type: "json" };\n`;
		output += `import { flattenChatModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";\n\n`;
		output += `export const ${catalogConstName(providerId)}: ChatModelCatalog<typeof values, ${JSON.stringify(providerId)}> =\n`;
		output += `\tflattenChatModelCatalog(${JSON.stringify(providerId)}, values);\n\n`;
		output += `export const ${imageCatalogConstName(providerId)}: ImageModelCatalog<typeof values, ${JSON.stringify(providerId)}> =\n`;
		output += `\tflattenImageModelCatalog(${JSON.stringify(providerId)}, values);\n`;
		const filename = `${providerId}.models.ts`;
		generatedShardFiles.add(filename);
		writeFileSync(join(providersDir, filename), output);
		}
		for (const entry of readdirSync(providersDir)) {
		if (entry.endsWith(".models.ts") && !generatedShardFiles.has(entry)) rmSync(join(providersDir, entry));
		}

		let output = generatedHeader;
		for (const providerId of providerIds) {
		output += `import { ${imageCatalogConstName(providerId)}, ${catalogConstName(providerId)} } from "./providers/${providerId}.models.ts";\n`;
		}
		const appendCatalog = (catalogName: string, name: (providerId: string) => string) => {
		output += `\nexport const ${catalogName}: {\n`;
		for (const providerId of providerIds) {
			output += `\treadonly ${JSON.stringify(providerId)}: typeof ${name(providerId)};\n`;
		}
		output += `} = {\n`;
		for (const providerId of providerIds) {
			output += `\t${JSON.stringify(providerId)}: ${name(providerId)},\n`;
		}
		output += "};\n";
		};
		appendCatalog("MODELS", catalogConstName);
		appendCatalog("IMAGE_MODELS", imageCatalogConstName);
		writeFileSync(aggregatorPath, output);
		return restore;
	} catch (error) {
		restore();
		throw error;
	}
}
